# Generated by Django 5.2.15 on 2026-07-10 15:29

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, upload_to=apps.products.models.product_og_upload_to),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.product_image_upload_to),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.variant_image_upload_to),
        ),
    ]
