# Generated by Django 5.2.15 on 2026-08-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_details_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postal_code',
        ),
    ]
