# Generated by Django 5.2.15 on 2026-09-04 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=250)),
                ('division_id', models.CharField(max_length=50)),
                ('division_name', models.CharField(max_length=100)),
                ('city_id', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=100)),
                ('area_id', models.CharField(max_length=50)),
                ('area_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default_shipping', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_shipping', True)), fields=('user',), name='unique_default_shipping_per_user')],
            },
        ),
    ]
